base_model: "unsloth/gemma-2-2b-bnb-4bit"
is_base_model: true
max_seq_length: 1024
load_in_4bit: true

lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
